package com.b1nd.dodam.designsystem.tokens

internal enum class DodamColorKeyTokens {
    PrimaryNormal,
    PrimaryStrong,
    PrimaryHeavy,
    LabelNormal,
    LabelStrong,
    LabelNeutral,
    LabelAlternative,
    LabelAssistive,
    LabelDisable,
    BackgroundNormalNormal,
    BackgroundNormalAlternative,
    BackgroundElevatedNormal,
    BackgroundElevatedAlternative,
    InteractionInactive,
    InteractionDisable,
    LineNormalNormal,
    LineNormalNeutral,
    LineNormalAlternative,
    LineNormalStrong,
    LineSolidNormal,
    LineSolidNeutral,
    LineSolidAlternative,
    LineSolidStrong,
    StatusPositive,
    StatusNegative,
    StatusCautionary,
    StaticWhite,
    StaticBlack
}